<?php
require_once 'config.php';
$pageTitle = 'COVID-19 Information | VitaSafe';
$activePage = 'info';
require 'partials/header.php';
?>
<section class="page-hero"><div class="container"><div class="eyebrow">THE ESSENTIALS</div><h1>Understand COVID-19.</h1><p>General educational information to help you make informed decisions. Always follow current local guidance.</p></div></section>
<section class="container content-layout section">
  <aside class="contents-card"><strong>On this page</strong><a href="#overview">Overview</a><a href="#symptoms">Symptoms</a><a href="#prevention">Prevention</a><a href="#when-to-get-help">When to get help</a><a href="#resources">Trusted resources</a></aside>
  <div class="article-content">
    <article class="info-block" id="overview"><span class="article-kicker">01 / OVERVIEW</span><h2>What is COVID-19?</h2><p>COVID-19 is an infectious respiratory disease caused by the SARS-CoV-2 virus. It can affect people differently, from mild illness to severe disease. Risk can be higher for older adults and people with certain underlying health conditions.</p><div class="notice"><strong>Remember</strong><p>This website is for a software-testing mini project and provides general information only. It cannot diagnose illness or replace advice from a healthcare professional.</p></div></article>
    <article class="info-block" id="symptoms"><span class="article-kicker">02 / SYMPTOMS</span><h2>Recognize possible symptoms</h2><p>Symptoms may vary and can overlap with other respiratory infections. Possible symptoms include:</p><div class="symptom-grid"><div>🌡️ <strong>Fever or chills</strong></div><div>😷 <strong>Cough</strong></div><div>🫁 <strong>Shortness of breath</strong></div><div>🪫 <strong>Fatigue</strong></div><div>🧠 <strong>Headache or body aches</strong></div><div>👃 <strong>Changes in taste or smell</strong></div><div>🤧 <strong>Sore throat or congestion</strong></div><div>🫧 <strong>Nausea or diarrhea</strong></div></div><p>Symptoms alone cannot confirm COVID-19. Testing and medical guidance may be appropriate depending on your situation and local recommendations.</p></article>
    <article class="info-block" id="prevention"><span class="article-kicker">03 / PREVENTION</span><h2>Practical ways to reduce risk</h2><div class="tip-list"><div><span>01</span><p><strong>Improve indoor air</strong><br>Open windows when appropriate, improve ventilation, or use suitable air filtration.</p></div><div><span>02</span><p><strong>Stay home when unwell</strong><br>Reduce contact with others when you have symptoms and follow local advice on returning to activities.</p></div><div><span>03</span><p><strong>Practice hand hygiene</strong><br>Wash hands regularly with soap and water or use hand sanitizer when needed.</p></div><div><span>04</span><p><strong>Consider a well-fitting mask</strong><br>A mask may offer added protection in crowded indoor spaces or when respiratory viruses are circulating.</p></div><div><span>05</span><p><strong>Keep vaccinations up to date</strong><br>Ask a qualified healthcare professional or local authority about recommendations for you.</p></div></div></article>
    <article class="info-block" id="when-to-get-help"><span class="article-kicker">04 / GETTING HELP</span><h2>When should you seek medical care?</h2><p>Contact a healthcare professional if you are concerned about symptoms, are at higher risk of severe illness, or need advice about testing or treatment. Seek emergency help for severe trouble breathing, persistent chest pain or pressure, new confusion, inability to stay awake, or pale/blue/grey lips or skin. Follow your local emergency guidance.</p></article>
    <article class="info-block" id="resources"><span class="article-kicker">05 / TRUSTED RESOURCES</span><h2>Check official guidance</h2><p>Public-health recommendations can change over time and differ by location. Use these recognized sources for the latest information:</p><div class="resource-links"><a href="https://www.who.int/health-topics/coronavirus" target="_blank" rel="noopener noreferrer"><span>World Health Organization</span><span>↗</span></a><a href="https://www.mohfw.gov.in/" target="_blank" rel="noopener noreferrer"><span>India Ministry of Health and Family Welfare</span><span>↗</span></a><a href="https://www.cdc.gov/covid/" target="_blank" rel="noopener noreferrer"><span>U.S. Centers for Disease Control and Prevention</span><span>↗</span></a></div></article>
  </div>
</section>
<?php require 'partials/footer.php'; ?>
